"""Initial migration with all tables including recipe status

Revision ID: 46f4e0f4c116
Revises: 
Create Date: 2026-04-17 11:36:39.500143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f4e0f4c116'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('babies', 'health_report_url')
    op.drop_column('recipe_details', 'recommendation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_details', sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('babies', sa.Column('health_report_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
